# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cab133656f19b7e7572a803a43d66e370e05408d713359cdf3d53eac6f0f88d080c99e856114feaccc5217155f050a3fca2e7a7b4518bd7b92fee5cd3c4f421

test:
  secret_key_base: 0ddeb05977c7e116076ded58a6d845c60b276157d297cca29360c665e3ca88a5d2b1619fbf78f11cef5c8040a14c12dacfe3bf457734caceb1cb5a5c19240d8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
